import * as fs from "fs";
import * as path from "path";
import { propertyId } from "./schemaKey";

// Read-only access to data/schema.json (generated by tools/generate-schema.js).

export interface PropertyInfo {
  name: string;
  count: number;
  kind: "boolean" | "number" | "enum" | "string";
  distinct: number;
  /** Most frequent vanilla values with their number of uses. */
  values: [string, number][];
  registry?: string;
  /** True when the value is a ";"-separated list. */
  list?: boolean;
  /** Valid values from a game registry, formatted like vanilla writes them. */
  suggestions?: string[];
  /** Vanilla sets this property several times in the same block (e.g. `row`). */
  repeatable?: boolean;
  /** Mods commonly add their own values: suggestions only, unknown values are not reported. */
  open?: boolean;
}

export interface BlockInfo {
  type: string;
  count: number;
  /** Every property the game reads is known: unknown properties can be reported. */
  strict: boolean;
  /** Child block types seen in vanilla ("component FluidContainer" for components) with their count. */
  children: Record<string, number>;
  /** First word of bare statements (e.g. `item` in recipe inputs) with their count. */
  statements: Record<string, number>;
  properties: Record<string, PropertyInfo>;
  /** Properties the game reads that no vanilla script uses (plausible names, suggested in completion). */
  extraKeys: string[];
  /** Every identifier of the game classes reading this block (lower-case): accepted by validation only. */
  acceptedKeys?: string[];
}

export interface SchemaData {
  gameVersion: string;
  generatedFrom: string;
  topLevel: string[];
  components: string[];
  recipeLines: { inputFlags: string[]; outputFlags: string[] };
  itemTypeProperties: Record<string, string[]>;
  blocks: Record<string, BlockInfo>;
}

/** Blocks that accept the same properties: an entity CraftRecipe component is a craftRecipe. */
const EQUIVALENT_KEYS: Record<string, string[]> = {
  craftrecipe: ["component:craftrecipe"],
  "component:craftrecipe": ["craftrecipe"],
  "craftrecipe/inputs": ["component:craftrecipe/inputs"],
  "component:craftrecipe/inputs": ["craftrecipe/inputs"],
  "craftrecipe/outputs": ["component:craftrecipe/outputs"],
  "component:craftrecipe/outputs": ["craftrecipe/outputs"],
};

/** Sub-blocks the game reads but that vanilla scripts may not use. */
const EXTRA_CHILD_BLOCKS: Record<string, string[]> = {
  craftrecipe: ["inputs", "outputs", "itemMapper", "fluidMapper", "energyMapper", "overlayMapper"],
  "component:craftrecipe": ["inputs", "outputs", "itemMapper", "fluidMapper", "energyMapper", "overlayMapper"],
  item: ["component"],
  entity: ["component"],
};

export interface KnownProperty {
  name: string;
  info?: PropertyInfo;
  /** Used by vanilla scripts (otherwise only known from the game code). */
  vanilla: boolean;
}

export class ScriptSchema {
  private readonly topLevelByLower: Map<string, string>;
  private readonly componentsByLower: Map<string, string>;
  private readonly propertiesCache = new Map<string, KnownProperty[]>();
  private readonly knownIdsCache = new Map<string, Set<string>>();

  constructor(readonly data: SchemaData) {
    this.topLevelByLower = new Map(data.topLevel.map((t) => [t.toLowerCase(), t]));
    this.componentsByLower = new Map(data.components.map((c) => [c.toLowerCase(), c]));
  }

  static fromFile(file: string): ScriptSchema {
    return new ScriptSchema(JSON.parse(fs.readFileSync(file, "utf8")) as SchemaData);
  }

  get gameVersion(): string {
    return this.data.gameVersion;
  }

  block(key: string): BlockInfo | undefined {
    return this.data.blocks[key];
  }

  private relatedKeys(key: string): string[] {
    return [key, ...(EQUIVALENT_KEYS[key] ?? [])];
  }

  /** A block is checked only if it and all its equivalents are strict. */
  isStrict(key: string): boolean {
    const blocks = this.relatedKeys(key).map((k) => this.block(k)).filter((b): b is BlockInfo => Boolean(b));
    return blocks.length > 0 && blocks.every((b) => b.strict);
  }

  property(key: string, name: string): PropertyInfo | undefined {
    const id = propertyId(name);
    for (const k of this.relatedKeys(key)) {
      const info = this.block(k)?.properties[id];
      if (info) return info;
    }
    return undefined;
  }

  isKnownProperty(key: string, name: string): boolean {
    let ids = this.knownIdsCache.get(key);
    if (!ids) {
      const accepted = this.relatedKeys(key).flatMap((k) => this.block(k)?.acceptedKeys ?? []);
      ids = new Set([...this.properties(key).map((p) => p.name.toLowerCase()), ...accepted]);
      this.knownIdsCache.set(key, ids);
    }
    return ids.has(propertyId(name));
  }

  /** Vanilla properties by frequency, then the ones only known from the game code. */
  properties(key: string): KnownProperty[] {
    let cached = this.propertiesCache.get(key);
    if (!cached) {
      cached = this.computeProperties(key);
      this.propertiesCache.set(key, cached);
    }
    return cached;
  }

  private computeProperties(key: string): KnownProperty[] {
    const seen = new Set<string>();
    const result: KnownProperty[] = [];
    const blocks = this.relatedKeys(key).map((k) => this.block(k)).filter((b): b is BlockInfo => Boolean(b));
    const vanilla = blocks.flatMap((b) => Object.values(b.properties)).sort((a, b) => b.count - a.count);
    for (const info of vanilla) {
      const id = info.name.toLowerCase();
      if (!seen.has(id)) {
        seen.add(id);
        result.push({ name: info.name, info, vanilla: true });
      }
    }
    for (const name of blocks.flatMap((b) => b.extraKeys)) {
      const id = name.toLowerCase();
      if (!seen.has(id) && !this.childBlockTypes(key).some((c) => c.toLowerCase() === id)) {
        seen.add(id);
        result.push({ name, vanilla: false });
      }
    }
    return result;
  }

  /** Child block types allowed in a block ("component" included when components are used). */
  childBlockTypes(key: string): string[] {
    const types = new Map<string, string>();
    for (const k of this.relatedKeys(key)) {
      for (const child of Object.keys(this.block(k)?.children ?? {})) {
        const type = child.split(" ")[0];
        types.set(type.toLowerCase(), type);
      }
      for (const type of EXTRA_CHILD_BLOCKS[k] ?? []) types.set(type.toLowerCase(), types.get(type.toLowerCase()) ?? type);
    }
    return [...types.values()];
  }

  /** Canonical name of a top-level block type, or undefined when the game does not know it. */
  topLevelType(type: string): string | undefined {
    return this.topLevelByLower.get(type.toLowerCase());
  }

  topLevelTypes(): string[] {
    return this.data.topLevel;
  }

  componentType(name: string): string | undefined {
    return this.componentsByLower.get(name.toLowerCase());
  }

  componentTypes(): string[] {
    return this.data.components.filter((c) => c !== "Undefined");
  }

  /** Component types seen in vanilla for a block kind (e.g. item → FluidContainer, Durability…). */
  vanillaComponents(key: string): string[] {
    return Object.keys(this.block(key)?.children ?? {})
      .filter((c) => c.startsWith("component "))
      .map((c) => c.slice("component ".length));
  }

  statementKeywords(key: string): string[] {
    const words = new Set<string>();
    for (const k of this.relatedKeys(key)) {
      for (const word of Object.keys(this.block(k)?.statements ?? {})) words.add(word);
    }
    return [...words];
  }

  recipeFlags(direction: "inputs" | "outputs"): string[] {
    return direction === "inputs" ? this.data.recipeLines.inputFlags : this.data.recipeLines.outputFlags;
  }

  /** Properties typical of an ItemType (e.g. `base:food`), lower-case. */
  itemTypeProperties(itemType: string): string[] {
    return this.data.itemTypeProperties[itemType.toLowerCase()] ?? [];
  }
}

let defaultSchema: ScriptSchema | undefined;

/** Schema shipped with the extension (data/schema.json next to out/). */
export function loadDefaultSchema(): ScriptSchema {
  defaultSchema ??= ScriptSchema.fromFile(path.join(__dirname, "..", "..", "data", "schema.json"));
  return defaultSchema;
}
